import './User.js'
import './Bot.js'
import './UsuarioBot.js'
import './Registro.js'
import './SolicitudUsuario.js'
import './Paciente.js'
import './HistoriaClinica.js'
import './TrazabilidadEnvio.js'
import './Notificacion.js'
import './RegistroGeneral.js'
import './Log.js'
import './AutorizacionBot.js'
import './Maquina.js'
import './asociations.js'
console.log('Models imported successfully');
